### ISSUE TITLE
Add missing prefixes to biolink model

### ISSUE THREAD

**Issue by matentzn** [everycure-org/matrix-validator#29]
@kevinschaper shared is breakdown of prefixes missing for RTX-KG2 in slack (see below).

This issue here is to track their inclusion into biolink.

```
prefixes_to_add_to_biolink:
  AEO: http://purl.obolibrary.org/obo/AEO_
  ARAPORT: http://identifiers.org/tair.name/
  ARO: http://purl.obolibrary.org/obo/ARO_
  ATC: http://identifiers.org/atc/
  BAO: http://identifiers.org/bao/
  CEPH: http://purl.obolibrary.org/obo/CEPH_
  CHMO: http://purl.obolibrary.org/obo/CHMO_
  CVDO: http://purl.obolibrary.org/obo/CVDO_
  ECCODE: http://identifiers.org/ec-code/
  ECOCORE: http://purl.obolibrary.org/obo/ECOCORE_
  ECOGENE: http://identifiers.org/ecogene/
  EDAM: http://identifiers.org/edam/
  EHDAA2: http://purl.obolibrary.org/obo/EHDAA2_
  EO: http://purl.obolibrary.org/obo/EO_
  EPO: http://purl.obolibrary.org/obo/EPO_
  ERO: http://purl.obolibrary.org/obo/ERO_
  FIX: http://purl.obolibrary.org/obo/FIX_
  GAZ: http://purl.obolibrary.org/obo/GAZ_
  GEO: http://purl.obolibrary.org/obo/GEO_
  ICO: http://purl.obolibrary.org/obo/ICO_
  MF: http://purl.obolibrary.org/obo/MF_
  MFOMD: http://purl.obolibrary.org/obo/MFOMD_
  MIRBASE: http://identifiers.org/mirbase/
  MMO: http://purl.obolibrary.org/obo/MMO_
  MOD: http://purl.obolibrary.org/obo/MOD_
  NCRO: http://purl.obolibrary.org/obo/NCRO_
  OAE: http://purl.obolibrary.org/obo/OAE_
  OBA: http://purl.obolibrary.org/obo/OBA_
  OGG: http://purl.obolibrary.org/obo/OGG_
  OMIABIS: http://purl.obolibrary.org/obo/OMIABIS_
  OMP: http://purl.obolibrary.org/obo/OMP_
  OMRSE: http://purl.obolibrary.org/obo/OMRSE_
  OPL: http://purl.obolibrary.org/obo/OPL_
  ORPHANET: http://identifiers.org/orphanet/
  PECO: http://purl.obolibrary.org/obo/PECO_
  SYMP: http://purl.obolibrary.org/obo/SYMP_
  TRANS: http://purl.obolibrary.org/obo/TRANS_
  TTD.TARGET: http://identifiers.org/ttd.target/
  UO: http://purl.obolibrary.org/obo/UO_
  VT: http://purl.obolibrary.org/obo/VT_
  ZEA: http://purl.obolibrary.org/obo/ZEA_
  cp: http://schemas.openxmlformats.org/package/2006/metadata/core-properties/
  dbpedia: http://dbpedia.org/resource/
  dc: http://purl.org/dc/elements/1.1/
  doap: http://usefulinc.com/ns/doap#
  obo: http://purl.obolibrary.org/obo/
  vcard: http://www.w3.org/2006/vcard/ns#
prefixes_to_fix:
  AraPort: ARAPORT
  CP: cp
  KEGG.ENZYME: ECCODE
  OBO: obo
  OIO: oboInOwl
  VCARD: vcard
  ecogene: ECOGENE
  miRBase: MIRBASE
  ttd.target: TTD.TARGET
  wb: WB
recognized_prefixes: []
unrecognized_prefixes:
- PathWhiz.Reaction
- PathWhiz.Compound
- CHV
- PathWhiz.ProteinComplex
- dictybase.gene
- FBgn
- PDQ
- PathWhiz.ElementCollection
- PSY
- PathWhiz.Bound
- CGNC
- EnsemblGenomes
- PathWhiz.NucleicAcid
- ICD10PCS
- UBPROP
- umls_source
- identifiers_org_registry
- TypOn
- RTX
- biolink_download_source
- UNICHEM_source
- JensenLab
- DisGeNET
- KEGG_source
```

## Action items:

- [ ] Determine where these prefixes `prefixes_to_add_to_biolink` need to be added. (@kevinschaper)
- [ ] Figure out if prefixes have to be added to specific classes in biolink to enable type inference in NN? (@jdr0887)
- [ ] Determine what to do about `unrecognized_prefixes` (@cbizon (Maybe with Kevin and Kathleen))
- [ ] The issue is completed if all prefixes in the above set are accounted for by some decision / solution
