### ISSUE TITLE
Create a system for managing exceptions to the biolink prefix requirement

### ISSUE THREAD

**Issue by matentzn** [everycure-org/matrix-validator#31]
In general, we want all prefixes to be biolink compatible. However, some legitimate prefixes are so far out of scope for biolink that it may not be useful to register them with biolink.

To maintain the integrity check and at the same time allow for such exceptions, we want to do the following:

1. Add a new CLI parameter `--exceptions exceptions.yml`

The format should be flexible as we might use it in the future for either kinds of configurations and other kinds of exceptions

```
exceptions:
   prefixes:
     - prefix: CHR
        description: This prefix is used to describe chromosomal locations in the monochrome ontology
     - prefix: CLYH
        description: This prefix refers to anatomical entities of the clytia hemispherica organism
```

2. Read the exception file, and during prefix checking, spit out a warning that the prefix is not biolink compliant but has been explicitly excluded from the check
3. Do not fail and proceed.
